### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by shalithasuranga** [99xt/walk2win#10]
Example : https://github.com/neutralinojs/neutralinojs/blob/master/CONTRIBUTING.md

**Comment by cazci** [comment]
Hi, there is already a code_of_conduct.md in the project root. Is it okay to update it or may I create a separate contributing.md file with reference to the example?

**Comment by afazdeen** [comment]
@cazci You can create a seperate contribution.md file in the project root.

**Comment by ThanoshanMV** [comment]
Hi. As the CONTRIBUTING.md file was added, please close this issue.

**Comment by alphagamer7** [comment]
#20  Closes this, thanks for pointing out @ThanoshanMV
